# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("stock", "0004_stockproduct_reporting_date")]

    operations = [
        migrations.AddField(
            model_name="dosage", name="rank", field=models.IntegerField(default=0)
        )
    ]
