# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("stock", "0021_auto_20170910_2134")]

    operations = [
        migrations.AddField(
            model_name="casespalucds",
            name="week_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="casespaludis",
            name="week_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="casespaluprov",
            name="week_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockproductcds",
            name="week_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockproductdis",
            name="week_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockproductprov",
            name="week_number",
            field=models.IntegerField(default=0),
        ),
    ]
